export type ContactPrefill = {
  topic?: string;
  role?: string;
  message?: string;
  organization?: string;
};

export function buildContactHref(prefill: ContactPrefill = {}): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(prefill)) {
    if (value?.trim()) {
      params.set(key, value.trim());
    }
  }
  const query = params.toString();
  return query ? `/contact-us?${query}` : '/contact-us';
}

export function downloadTextFile(filename: string, content: string, mime = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadCsv(
  filename: string,
  rows: Record<string, string | number>[],
  columns: { key: string; label: string }[]
) {
  const escape = (value: string | number) => {
    const text = String(value);
    if (/[",\n]/.test(text)) {
      return `"${text.replace(/"/g, '""')}"`;
    }
    return text;
  };

  const header = columns.map((col) => escape(col.label)).join(',');
  const body = rows
    .map((row) => columns.map((col) => escape(row[col.key] ?? '')).join(','))
    .join('\n');

  downloadTextFile(filename, `${header}\n${body}`, 'text/csv;charset=utf-8');
}

export function openFilePicker(options: { accept?: string; onSelect: (file: File) => void }) {
  const input = document.createElement('input');
  input.type = 'file';
  if (options.accept) {
    input.accept = options.accept;
  }
  input.onchange = () => {
    const file = input.files?.[0];
    if (file) {
      options.onSelect(file);
    }
  };
  input.click();
}

export function scrollToElementId(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

export type CareerProfileExport = {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  headline: string;
  completionScore: number;
  education: { school: string; degree: string; year: string }[];
  skills: { name: string; level: number }[];
  certificates: { name: string; issuer: string; year: string }[];
  experience: { role: string; company: string; period: string; description: string }[];
  languages: { name: string; level: string }[];
};

export function formatCareerProfileDocument(profile: CareerProfileExport, format: 'cv' | 'pdf-text' = 'cv') {
  const lines: string[] = [];
  const divider = '—'.repeat(48);

  lines.push(profile.fullName || 'HDP EDU Profile');
  if (profile.headline) lines.push(profile.headline);
  lines.push('');
  lines.push(`Email: ${profile.email}`);
  if (profile.phone) lines.push(`Phone: ${profile.phone}`);
  if (profile.location) lines.push(`Location: ${profile.location}`);
  lines.push(`Profile completion: ${profile.completionScore}%`);
  lines.push(divider);

  if (profile.experience.length) {
    lines.push('', 'EXPERIENCE');
    for (const exp of profile.experience) {
      lines.push(`${exp.role} — ${exp.company} (${exp.period})`);
      if (exp.description) lines.push(exp.description);
      lines.push('');
    }
  }

  if (profile.education.length) {
    lines.push('EDUCATION');
    for (const edu of profile.education) {
      lines.push(`${edu.degree} — ${edu.school} (${edu.year})`);
    }
    lines.push('');
  }

  if (profile.skills.length) {
    lines.push('SKILLS');
    lines.push(profile.skills.map((skill) => `${skill.name} (${skill.level}%)`).join(' · '));
    lines.push('');
  }

  if (profile.certificates.length) {
    lines.push('CERTIFICATES');
    for (const cert of profile.certificates) {
      lines.push(`${cert.name} — ${cert.issuer} (${cert.year})`);
    }
    lines.push('');
  }

  if (profile.languages.length) {
    lines.push('LANGUAGES');
    lines.push(profile.languages.map((lang) => `${lang.name}: ${lang.level}`).join(' · '));
    lines.push('');
  }

  lines.push(divider);
  lines.push(format === 'cv' ? 'Generated by HDP EDU — hdpedu.com' : 'HDP EDU Profile Export — hdpedu.com');

  return lines.join('\n');
}
