import type { ExpertEvent, ExpertProfile } from './types';

export const MOCK_EXPERTS: ExpertProfile[] = [
  {
    id: 'ex1',
    name: 'PGS.TS Nguyễn Đình Tuấn',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Giáo dục',
    country: 'Việt Nam',
    biography: '30 năm kinh nghiệm đào tạo và tư vấn chiến lược giáo dục. Cựu Hiệu trưởng, cố vấn cho hơn 40 trung tâm đào tạo tại Việt Nam và khu vực.',
    expertise: ['Chiến lược đào tạo', 'Quản trị trung tâm', 'EdTech'],
    experience: '30 năm',
    certifications: ['PhD Education Leadership', 'Cambridge DELTA'],
    rating: 4.9,
  },
  {
    id: 'ex2',
    name: 'Dr. Sarah Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Công nghệ',
    country: 'Singapore',
    biography: 'Chuyên gia AI và chuyển đổi số doanh nghiệp tại APAC. Từng dẫn dắt các dự án công nghệ quy mô lớn cho tập đoàn đa quốc gia.',
    expertise: ['AI Strategy', 'Digital Transformation', 'Product Innovation'],
    experience: '18 năm',
    certifications: ['AWS Solutions Architect', 'MIT AI Program'],
    rating: 4.8,
  },
  {
    id: 'ex3',
    name: 'Trần Hoàng Long',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Tài chính',
    country: 'Việt Nam',
    biography: 'Cựu Giám đốc đầu tư tại quỹ đầu tư tư nhân, chuyên tư vấn M&A, quản trị rủi ro và chiến lược tài chính doanh nghiệp.',
    expertise: ['Đầu tư', 'M&A', 'Risk Management'],
    experience: '22 năm',
    certifications: ['CFA', 'FRM'],
    rating: 4.7,
  },
  {
    id: 'ex4',
    name: 'Prof. Kim Min-jae',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Xuất khẩu lao động',
    country: 'Hàn Quốc',
    biography: 'Giáo sư tư vấn việc làm và định cư nghề nghiệp tại Hàn Quốc. Hỗ trợ hàng nghìn lao động Việt Nam làm việc tại các doanh nghiệp Hàn.',
    expertise: ['EPS', 'Visa E-7', 'Korean Workplace Culture'],
    experience: '15 năm',
    certifications: ['TOPIK Level 6', 'Korean Employment Law Certificate'],
    rating: 4.6,
  },
  {
    id: 'ex5',
    name: 'Dr. Park Ji-hoon',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Giáo dục',
    country: 'Hàn Quốc',
    biography: 'Tiến sĩ Ngôn ngữ học, chuyên gia đào tạo tiếng Hàn cho người Việt. Phát triển chương trình TOPIK và giáo trình giao tiếp thực tế.',
    expertise: ['TOPIK Preparation', 'Korean Linguistics', 'Curriculum Design'],
    experience: '12 năm',
    certifications: ['PhD Korean Linguistics', 'TOPIK Examiner'],
    rating: 4.9,
  },
  {
    id: 'ex6',
    name: 'Lê Phương Anh',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Nhân sự',
    country: 'Việt Nam',
    biography: 'Cựu Giám đốc Nhân sự tại tập đoàn đa quốc gia, chuyên tư vấn tuyển dụng, phát triển năng lực và xây dựng văn hóa doanh nghiệp.',
    expertise: ['Talent Acquisition', 'Employer Branding', 'HR Strategy'],
    experience: '16 năm',
    certifications: ['SHRM-SCP', 'CIPD Level 7'],
    rating: 4.8,
  },
  {
    id: 'ex7',
    name: 'James Morrison',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Ngoại thương',
    country: 'Singapore',
    biography: 'Chuyên gia thương mại quốc tế với kinh nghiệm xây dựng chuỗi cung ứng Việt Nam – ASEAN – Hàn Quốc cho doanh nghiệp SME.',
    expertise: ['Import/Export', 'Supply Chain', 'Trade Compliance'],
    experience: '20 năm',
    certifications: ['CITP', 'Incoterms 2020 Certified'],
    rating: 4.7,
  },
  {
    id: 'ex8',
    name: 'Ngô Minh Khang',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Luật',
    country: 'Việt Nam',
    biography: 'Luật sư tư vấn pháp lý lao động, định cư và hợp đồng quốc tế. Hỗ trợ doanh nghiệp và cá nhân trong các thủ tục xuất khẩu lao động.',
    expertise: ['Labor Law', 'Immigration', 'International Contracts'],
    experience: '14 năm',
    certifications: ['Bar Association VN', 'ILO Labor Standards'],
    rating: 4.6,
  },
  {
    id: 'ex9',
    name: 'Dr. Yuki Tanaka',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Công nghệ',
    country: 'Nhật Bản',
    biography: 'Kỹ sư trưởng với kinh nghiệm phát triển sản phẩm công nghệ giáo dục tại Tokyo. Tư vấn EdTech và trải nghiệm học tập số.',
    expertise: ['EdTech Product', 'UX for Learning', 'SaaS Growth'],
    experience: '11 năm',
    certifications: ['PMP', 'Google UX Design'],
    rating: 4.8,
  },
  {
    id: 'ex10',
    name: 'Phạm Thu Hà',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Giáo dục',
    country: 'Việt Nam',
    biography: 'Chuyên gia thiết kế chương trình đào tạo tiếng Hàn cho doanh nghiệp. Đã triển khai chương trình đào tạo nội bộ cho 25+ công ty.',
    expertise: ['Corporate Training', 'Korean for Business', 'Learning Design'],
    experience: '10 năm',
    certifications: ['TOPIK Level 5', 'Instructional Design Certificate'],
    rating: 4.7,
  },
  {
    id: 'ex11',
    name: 'Dr. Elena Vasquez',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Ngoại thương',
    country: 'Việt Nam',
    biography: 'Cố vấn thương mại và phát triển thị trường, chuyên kết nối doanh nghiệp Việt với đối tác Hàn Quốc và châu Âu.',
    expertise: ['Market Entry', 'B2B Partnerships', 'Cross-border Trade'],
    experience: '13 năm',
    certifications: ['MBA International Business', 'KOTRA Trade Advisor'],
    rating: 4.9,
  },
  {
    id: 'ex12',
    name: 'Hoàng Quốc Bảo',
    avatarUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?crop=faces&fit=crop&w=256&h=256&q=80',
    industry: 'Nhân sự',
    country: 'Hàn Quốc',
    biography: 'Chuyên gia tuyển dụng và hội nhập lao động Việt tại Hàn Quốc. Tư vấn hồ sơ, phỏng vấn và thích nghi môi trường làm việc.',
    expertise: ['Korean Job Market', 'CV & Interview', 'Cultural Integration'],
    experience: '9 năm',
    certifications: ['TOPIK Level 6', 'Career Coach Certification'],
    rating: 4.5,
  },
];

export const MOCK_EVENTS: ExpertEvent[] = [
  { id: 'ev1', title: 'Xu hướng EdTech 2026', category: 'webinar', date: '2026-06-15', time: '19:00', speakers: ['PGS.TS Nguyễn Đình Tuấn'], registered: 186, capacity: 300, isOnline: true },
  { id: 'ev2', title: 'Workshop: AI cho Doanh nghiệp SME', category: 'workshop', date: '2026-06-20', time: '09:00', speakers: ['Dr. Sarah Chen', 'Trần Hoàng Long'], registered: 42, capacity: 50, isOnline: false },
  { id: 'ev3', title: 'Diễn đàn Xuất khẩu lao động Hàn Quốc', category: 'trade_forum', date: '2026-07-05', time: '14:00', speakers: ['Prof. Kim Min-jae'], registered: 320, capacity: 500, isOnline: true },
  { id: 'ev4', title: 'Networking: Founders & Investors', category: 'networking', date: '2026-06-28', time: '18:30', speakers: ['Trần Hoàng Long'], registered: 68, capacity: 80, isOnline: false },
];

export const EVENT_CATEGORY_LABELS: Record<ExpertEvent['category'], string> = {
  webinar: 'Webinar',
  workshop: 'Workshop',
  trade_forum: 'Diễn đàn',
  networking: 'Networking',
};
