import type { GeneratedQuestion } from '@/lib/tests/schemas';
import type { TestDifficulty, TestSource } from '@/lib/tests/types';

export interface CuratedTestSeed {
  externalId: string;
  fieldId: string;
  title: string;
  topicIndex: number;
  variant: number;
  difficulty: TestDifficulty;
  durationMinutes: number;
  source: TestSource;
  featured: boolean;
  popularity: number;
  description: string;
  questions: GeneratedQuestion[];
}

export const CURATED_FLAGSHIP_TESTS: CuratedTestSeed[] = [
  {
    externalId: 'topik-mock-1',
    fieldId: 'topik_exam',
    title: 'TOPIK I Mock Exam #1',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 45,
    source: 'curated',
    featured: true,
    popularity: 892,
    description: 'Full-length TOPIK I style practice with reading, grammar, and vocabulary.',
    questions: [
      {
        type: 'multiple_choice',
        prompt: 'What does "학교" mean?',
        options: ['School', 'Hospital', 'Company', 'Library'],
        correctIndex: 0,
        modelAnswer: 'School',
        rubric: 'Correct meaning of 학교.',
        explanation: '학교 (hakgyo) = school.',
      },
      {
        type: 'fill_blank',
        prompt: 'Fill in the particle: 저는 ___ 에서 왔어요. (Vietnam)',
        modelAnswer: '베트남',
        rubric: 'Country name in Korean acceptable: 베트남.',
        acceptableVariants: ['베트남', 'vietnam'],
        maxLength: 50,
      },
      {
        type: 'translation',
        prompt: 'Translate to Korean: "Nice to meet you."',
        modelAnswer: '만나서 반갑습니다.',
        rubric: 'Polite greeting form required.',
        acceptableVariants: ['만나서 반갑습니다', '만나서 반가워요.'],
        maxLength: 80,
      },
      {
        type: 'multiple_choice',
        prompt: 'Choose the correct past tense of 가다:',
        options: ['간다', '갔다', '갈 거예요', '가세요'],
        correctIndex: 1,
        modelAnswer: '갔다',
        rubric: 'Basic past tense form.',
      },
      {
        type: 'short_answer',
        prompt: 'Write one formal self-introduction sentence in Korean including your name.',
        modelAnswer: '안녕하세요, 저는 [이름]입니다.',
        rubric: 'Must include greeting, 저는, and copula ending.',
        maxLength: 150,
      },
      {
        type: 'reading_comprehension',
        passage: '민수는 매일 아침 7시에 일어납니다. 학교에 가기 전에 아침을 먹습니다.',
        prompt: 'What does Min-su do before going to school?',
        modelAnswer: '아침을 먹습니다 / eats breakfast',
        rubric: 'Answer must mention eating breakfast.',
        maxLength: 100,
      },
      {
        type: 'fill_blank',
        prompt: 'Complete: 저는 학생___. (polite formal)',
        modelAnswer: '입니다',
        rubric: 'Formal copula ending.',
        acceptableVariants: ['입니다.', '입니다'],
        maxLength: 30,
      },
      {
        type: 'sentence_order',
        prompt: 'Arrange into a correct Korean sentence: [갑니다 / 학교에 / 저는]',
        modelAnswer: '저는 학교에 갑니다.',
        rubric: 'Correct SOV order with topic and location.',
        acceptableVariants: ['저는 학교에 갑니다', '저는 학교에 갑니다.'],
        maxLength: 80,
      },
    ],
  },
  {
    externalId: 'topik-mock-2',
    fieldId: 'topik_exam',
    title: 'TOPIK II Reading & Grammar #1',
    topicIndex: 2,
    variant: 1,
    difficulty: 'intermediate',
    durationMinutes: 60,
    source: 'curated',
    featured: true,
    popularity: 654,
    description: 'Intermediate TOPIK II style grammar and reading comprehension.',
    questions: [
      {
        type: 'multiple_choice',
        prompt: 'Select the correct connector: 공부를 열심히 ___ 시험에 합격했습니다.',
        options: ['하지만', '해서', '해도', '하거나'],
        correctIndex: 1,
        modelAnswer: '해서',
        rubric: 'Causal connector 해서.',
      },
      {
        type: 'translation',
        prompt: 'Translate to Korean: "Because the weather is cold, I wear a coat."',
        modelAnswer: '날씨가 추워서 코트를 입습니다.',
        rubric: 'Use -아/어서 or similar causal form.',
        maxLength: 120,
      },
      {
        type: 'reading_comprehension',
        passage:
          '환경 보호는 현대 사회의 중요한 과제입니다. 많은 기업이 친환경 정책을 도입하고 있습니다.',
        prompt: 'Summarize the main idea in one sentence (Korean or Vietnamese).',
        modelAnswer: '환경 보호가 중요하고 기업들이 친환경 정책을 도입하고 있다.',
        rubric: 'Must mention environmental protection and corporate action.',
        maxLength: 200,
      },
      {
        type: 'fill_blank',
        prompt: 'Honorific form of 먹다 when speaking about a teacher: 선생님께서 ___.',
        modelAnswer: '드십니다',
        rubric: 'Correct honorific verb form.',
        acceptableVariants: ['드십니다', '드십니다.'],
        maxLength: 40,
      },
      {
        type: 'short_answer',
        prompt: 'Explain the difference between 은/는 and 이/가 in one or two sentences.',
        modelAnswer: '은/는 marks the topic; 이/가 marks the subject, often introducing new information.',
        rubric: 'Must distinguish topic vs subject.',
        maxLength: 250,
      },
      {
        type: 'multiple_choice',
        prompt: 'Best expression for "I intend to study abroad":',
        options: ['유학을 가고 싶어요', '유학을 갔어요', '유학을 가세요', '유학을 가지 마세요'],
        correctIndex: 0,
        modelAnswer: '유학을 가고 싶어요',
        rubric: 'Desire/intention form.',
      },
      {
        type: 'translation',
        prompt: 'Translate to English: "회의가 오후 3시에 시작됩니다."',
        modelAnswer: 'The meeting starts at 3 PM.',
        rubric: 'Correct time and meeting translation.',
        maxLength: 100,
      },
      {
        type: 'sentence_order',
        prompt: 'Order correctly: [한국어 / 배우고 / 3년째 / 저는]',
        modelAnswer: '저는 3년째 한국어를 배우고 있습니다.',
        rubric: 'Natural progressive with duration.',
        maxLength: 100,
      },
    ],
  },
  {
    externalId: 'korean-vocab-daily-1',
    fieldId: 'korean_vocabulary',
    title: 'Daily Korean Vocabulary — Set 1',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 25,
    source: 'curated',
    featured: true,
    popularity: 421,
    description: 'Essential daily vocabulary with typed recall and translation.',
    questions: [
      { type: 'multiple_choice', prompt: '"친구" means:', options: ['Friend', 'Teacher', 'Food', 'Book'], correctIndex: 0, modelAnswer: 'Friend', rubric: 'Vocabulary meaning.' },
      { type: 'fill_blank', prompt: 'Write the Korean word for "water":', modelAnswer: '물', rubric: 'Correct Hangul.', acceptableVariants: ['물'], maxLength: 20 },
      { type: 'translation', prompt: 'Translate to Korean: "book"', modelAnswer: '책', rubric: 'Single noun.', maxLength: 20 },
      { type: 'fill_blank', prompt: 'Antonym of "크다" (big):', modelAnswer: '작다', rubric: 'Antonym vocabulary.', maxLength: 20 },
      { type: 'short_answer', prompt: 'Use "공부하다" in a complete sentence.', modelAnswer: '저는 한국어를 공부합니다.', rubric: 'Must use 공부하다 correctly.', maxLength: 100 },
      { type: 'multiple_choice', prompt: '"병원" is:', options: ['Hospital', 'Bank', 'Market', 'Station'], correctIndex: 0, modelAnswer: 'Hospital', rubric: 'Noun meaning.' },
      { type: 'translation', prompt: 'Translate: "오늘 날씨가 좋아요."', modelAnswer: 'The weather is nice today.', rubric: 'Natural English.', maxLength: 80 },
      { type: 'fill_blank', prompt: 'Korean for "to eat" (dictionary form):', modelAnswer: '먹다', rubric: 'Verb dictionary form.', maxLength: 20 },
    ],
  },
  {
    externalId: 'korean-grammar-particles-1',
    fieldId: 'korean_grammar',
    title: 'Korean Particles Master — Set 1',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 30,
    source: 'curated',
    featured: true,
    popularity: 388,
    description: 'Deep practice on 은/는, 이/가, 을/를, 에/에서.',
    questions: [
      { type: 'fill_blank', prompt: '저___ 학생입니다. (topic particle)', modelAnswer: '는', rubric: 'Topic particle after 저.', maxLength: 10 },
      { type: 'fill_blank', prompt: '책___ 읽습니다. (object particle)', modelAnswer: '을', rubric: 'Object marker.', maxLength: 10 },
      { type: 'multiple_choice', prompt: 'Location of action (studying AT library):', options: ['도서관에', '도서관에서', '도서관을', '도서관은'], correctIndex: 1, modelAnswer: '도서관에서', rubric: 'Action location particle.' },
      { type: 'short_answer', prompt: 'Explain when to use 에 vs 에서 with one example each.', modelAnswer: '에 for destination/static location; 에서 for action location.', rubric: 'Both particles explained.', maxLength: 200 },
      { type: 'sentence_order', prompt: 'Order: [한국어 / 공부합니다 / 학교에서 / 저는]', modelAnswer: '저는 학교에서 한국어를 공부합니다.', rubric: 'Correct particles and order.', maxLength: 80 },
      { type: 'translation', prompt: 'Translate: "I go to the office by bus."', modelAnswer: '저는 버스로 회사에 갑니다.', rubric: 'Use 로 for means and 에 for destination.', maxLength: 100 },
      { type: 'fill_blank', prompt: '친구___ 만났습니다. (meet a friend - object)', modelAnswer: '를', rubric: 'Object particle.', maxLength: 10 },
      {
        type: 'multiple_choice',
        prompt: 'Correct subject marker after "books" (책, plural implied):',
        options: ['책은', '책이', '책을', '책에'],
        correctIndex: 1,
        modelAnswer: '책이',
        rubric: 'Subject focus particle 이 after consonant-ending noun.',
      },
    ],
  },
  {
    externalId: 'korean-reading-signs-1',
    fieldId: 'korean_reading',
    title: 'Reading Korean Signs & Notices',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 25,
    source: 'curated',
    featured: true,
    popularity: 312,
    description: 'Read real-world signs and short notices.',
    questions: [
      { type: 'translation', prompt: 'Translate sign: "출입 금지"', modelAnswer: 'No entry', rubric: 'Common sign.', maxLength: 40 },
      { type: 'multiple_choice', prompt: '"화장실" means:', options: ['Restroom', 'Office', 'Kitchen', 'Elevator'], correctIndex: 0, modelAnswer: 'Restroom', rubric: 'Public sign vocab.' },
      { type: 'fill_blank', prompt: '"Push" on a door is usually:', modelAnswer: '미는', rubric: 'Accept 미세요 or 밀어.', acceptableVariants: ['미세요', '밀어', 'PUSH'], maxLength: 30 },
      { type: 'reading_comprehension', passage: '오늘은 휴무입니다. 내일 정상 영업합니다.', prompt: 'Is the store open today?', modelAnswer: 'No / closed today', rubric: 'Understand 휴무.', maxLength: 60 },
      { type: 'translation', prompt: 'Translate: "할인 30%"', modelAnswer: '30% discount', rubric: 'Sale sign.', maxLength: 40 },
      { type: 'short_answer', prompt: 'What would you do if you see "조용히 해주세요"?', modelAnswer: 'Be quiet / keep quiet', rubric: 'Meaning of request.', maxLength: 80 },
      { type: 'fill_blank', prompt: 'Emergency phone number in Korea:', modelAnswer: '119', rubric: 'Fire/rescue or 112 police acceptable if explained.', acceptableVariants: ['119', '112'], maxLength: 10 },
      { type: 'multiple_choice', prompt: '"금연" zone means:', options: ['No smoking', 'No parking', 'No photos', 'No food'], correctIndex: 0, modelAnswer: 'No smoking', rubric: 'Public notice.' },
    ],
  },
  {
    externalId: 'business-korean-email-1',
    fieldId: 'business_korean',
    title: 'Business Korean — Email & Meetings',
    topicIndex: 1,
    variant: 1,
    difficulty: 'intermediate',
    durationMinutes: 35,
    source: 'curated',
    featured: true,
    popularity: 276,
    description: 'Professional Korean for workplace communication.',
    questions: [
      { type: 'translation', prompt: 'Translate: "Thank you for your email." (formal)', modelAnswer: '메일 잘 받았습니다.', rubric: 'Business email phrase.', maxLength: 80 },
      { type: 'fill_blank', prompt: 'Meeting in Korean (noun):', modelAnswer: '회의', rubric: 'Business vocab.', maxLength: 20 },
      { type: 'short_answer', prompt: 'Write a formal meeting request subject line in Korean.', modelAnswer: '회의 일정 요청드립니다.', rubric: 'Formal business tone.', maxLength: 100 },
      { type: 'multiple_choice', prompt: 'Polite way to say "I will attend":', options: ['참석하겠습니다', '참석해', '참석했다', '참석마'], correctIndex: 0, modelAnswer: '참석하겠습니다', rubric: 'Future formal.' },
      { type: 'translation', prompt: 'Translate: "Please review the attached file."', modelAnswer: '첨부 파일 확인 부탁드립니다.', rubric: 'Business request.', maxLength: 100 },
      { type: 'sentence_order', prompt: 'Order: [드리겠습니다 / 자료를 / 회의 / 전]', modelAnswer: '회의 자료를 전 드리겠습니다.', rubric: 'Formal offer.', maxLength: 80 },
      { type: 'fill_blank', prompt: 'Boss honorific title (commonly):', modelAnswer: '부장님', rubric: 'Accept 팀장님 etc. if workplace appropriate.', acceptableVariants: ['부장님', '팀장님', '사장님'], maxLength: 30 },
      { type: 'short_answer', prompt: 'One sentence declining a meeting politely in Korean.', modelAnswer: '죄송하지만 해당 시간에 참석이 어렵습니다.', rubric: 'Polite decline.', maxLength: 150 },
    ],
  },
  {
    externalId: 'korean-writing-formal-1',
    fieldId: 'korean_writing',
    title: 'Korean Writing — Formal Paragraph',
    topicIndex: 1,
    variant: 1,
    difficulty: 'intermediate',
    durationMinutes: 40,
    source: 'curated',
    featured: true,
    popularity: 198,
    description: 'Write formal sentences and short paragraphs.',
    questions: [
      { type: 'short_answer', prompt: 'Write 2–3 sentences introducing why you study Korean.', modelAnswer: '한국어를 배우는 이유는 한국에서 일하고 싶기 때문입니다. ...', rubric: 'Coherent reason, formal endings preferred.', maxLength: 400 },
      { type: 'translation', prompt: 'Translate formally: "I look forward to your reply."', modelAnswer: '답장 기다리겠습니다.', rubric: 'Formal closing.', maxLength: 80 },
      { type: 'fill_blank', prompt: 'Formal ending for "thank you" (written):', modelAnswer: '감사합니다', rubric: 'Standard formal thanks.', maxLength: 30 },
      { type: 'sentence_order', prompt: 'Order essay opener: [저는 / 한국 문화에 / 관심이 / 많습니다]', modelAnswer: '저는 한국 문화에 관심이 많습니다.', rubric: 'Natural written opener.', maxLength: 80 },
      { type: 'multiple_choice', prompt: 'Most formal closing for a report:', options: ['끝', '以上', '감사합니다', 'ㅋㅋ'], correctIndex: 2, modelAnswer: '감사합니다', rubric: 'Formal report closing.' },
      { type: 'short_answer', prompt: 'Rewrite informally "밥 먹었어?" to formal speech.', modelAnswer: '식사 하셨습니까?', rubric: 'Honorific/formal question.', maxLength: 80 },
    ],
  },
  {
    externalId: 'korean-culture-traditions-1',
    fieldId: 'korean_culture',
    title: 'Korean Culture & Traditions',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 25,
    source: 'curated',
    featured: true,
    popularity: 245,
    description: 'Culture, holidays, etiquette, and daily life in Korea.',
    questions: [
      { type: 'multiple_choice', prompt: 'Seollal is:', options: ['Lunar New Year', 'Mid-autumn Festival', 'Independence Day', 'Children\'s Day'], correctIndex: 0, modelAnswer: 'Lunar New Year', rubric: 'Holiday knowledge.' },
      { type: 'short_answer', prompt: 'Describe one bow etiquette rule in Korea.', modelAnswer: 'Bow when greeting elders; deeper bow for formal respect.', rubric: 'Etiquette explanation.', maxLength: 150 },
      { type: 'translation', prompt: 'Translate: "추석"', modelAnswer: 'Chuseok / Korean harvest festival', rubric: 'Festival name.', maxLength: 60 },
      { type: 'fill_blank', prompt: 'Traditional Korean clothing:', modelAnswer: '한복', rubric: 'Hanbok.', maxLength: 20 },
      { type: 'reading_comprehension', passage: '한국에서는 신발을 벗고 실내에 들어가는 경우가 많습니다.', prompt: 'What custom is described?', modelAnswer: 'Removing shoes indoors', rubric: 'Cultural practice.', maxLength: 80 },
      { type: 'multiple_choice', prompt: 'Age hierarchy affects:', options: ['Speech formality', 'Weather', 'Currency', 'Traffic laws'], correctIndex: 0, modelAnswer: 'Speech formality', rubric: 'Social hierarchy.' },
    ],
  },
  {
    externalId: 'korean-listening-phrases-1',
    fieldId: 'korean_listening',
    title: 'Korean Listening — Key Phrases',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 25,
    source: 'curated',
    featured: true,
    popularity: 267,
    description: 'Common spoken phrases and appropriate responses (text-based listening prep).',
    questions: [
      { type: 'translation', prompt: 'You hear "어서 오세요" at a shop. What does it mean?', modelAnswer: 'Welcome (come in)', rubric: 'Store greeting.', maxLength: 60 },
      { type: 'fill_blank', prompt: 'Response to "감사합니다":', modelAnswer: '천만에요', rubric: 'Accept 아니에요.', acceptableVariants: ['천만에요', '아니에요', '별말씀을요'], maxLength: 40 },
      { type: 'multiple_choice', prompt: '"잠시만요" means:', options: ['Wait a moment', 'Goodbye forever', 'I am angry', 'Come here now'], correctIndex: 0, modelAnswer: 'Wait a moment', rubric: 'Spoken phrase.' },
      { type: 'short_answer', prompt: 'What do you reply when someone asks "어디 가요?"', modelAnswer: '학교에 가요 / 회사에 가요 (any valid destination)', rubric: 'Destination answer.', maxLength: 80 },
      { type: 'translation', prompt: 'Translate: "한 잔만 더 주세요."', modelAnswer: 'Please give me one more cup/glass.', rubric: 'Restaurant phrase.', maxLength: 80 },
      { type: 'sentence_order', prompt: 'Phone greeting order: [여보세요 / 안녕하세요 / OOO입니다]', modelAnswer: '여보세요, 안녕하세요. OOO입니다.', rubric: 'Phone intro pattern.', maxLength: 80 },
    ],
  },
  {
    externalId: 'english-for-korean-learners-1',
    fieldId: 'english_skills',
    title: 'English for Korean Learners — Set 1',
    topicIndex: 1,
    variant: 1,
    difficulty: 'beginner',
    durationMinutes: 25,
    source: 'curated',
    featured: true,
    popularity: 189,
    description: 'English support skills for students studying in Korea.',
    questions: [
      { type: 'multiple_choice', prompt: 'Correct: "She ___ to Seoul last year."', options: ['go', 'goes', 'went', 'going'], correctIndex: 2, modelAnswer: 'went', rubric: 'Past tense.' },
      { type: 'fill_blank', prompt: 'Fill in: "I am interested ___ learning Korean."', modelAnswer: 'in', rubric: 'Preposition.', maxLength: 10 },
      { type: 'translation', prompt: 'Translate to English: "저는 베트남 사람입니다."', modelAnswer: 'I am Vietnamese.', rubric: 'Nationality sentence.', maxLength: 60 },
      { type: 'short_answer', prompt: 'Write one sentence about your study goal in English.', modelAnswer: 'I want to pass TOPIK level 3.', rubric: 'Grammatical sentence with goal.', maxLength: 150 },
      { type: 'sentence_order', prompt: 'Order: [Korean / studying / am / I]', modelAnswer: 'I am studying Korean.', rubric: 'Present continuous.', maxLength: 60 },
      { type: 'fill_blank', prompt: 'Plural of "child":', modelAnswer: 'children', rubric: 'Irregular plural.', maxLength: 20 },
    ],
  },
];
